"""added sync date

Revision ID: 9ffe47fb5d4a
Revises: fd8b14a71c62
Create Date: 2023-01-25 10:06:30.654072

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffe47fb5d4a'
down_revision = 'fd8b14a71c62'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order', sa.Column('sync_date', sa.String(length=25), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order', 'sync_date')
    # ### end Alembic commands ###
