"""changed table order to orders

Revision ID: d405c6cb616b
Revises: 9ffe47fb5d4a
Create Date: 2023-01-25 13:30:44.343666

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd405c6cb616b'
down_revision = '9ffe47fb5d4a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=True),
    sa.Column('keywork', sa.String(length=50), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('result_date', sa.String(length=25), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('is_sync_allowed', sa.Boolean(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('sync_date', sa.String(length=25), nullable=True),
    sa.Column('sync_comment', sa.String(length=255), nullable=True),
    sa.Column('raw_data_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_data_uid'], ['raw_data.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_orders_uid'), 'orders', ['uid'], unique=False)
    op.drop_index('ix_order_uid', table_name='order')
    op.drop_table('order')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('order',
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp() ON UPDATE current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text("'0000-00-00 00:00:00'"), nullable=False),
    sa.Column('uid', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('order_id', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('test_id', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('keywork', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('instrument', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('result', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('result_date', mysql.VARCHAR(length=25), nullable=False),
    sa.Column('unit', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('comment', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_sync_allowed', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('synced', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('sync_comment', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('raw_data_uid', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('sync_date', mysql.VARCHAR(length=25), nullable=True),
    sa.ForeignKeyConstraint(['raw_data_uid'], ['raw_data.uid'], name='order_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_order_uid', 'order', ['uid'], unique=False)
    op.drop_index(op.f('ix_orders_uid'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
