"""added splits

Revision ID: f1db4f15b5f8
Revises: d405c6cb616b
Create Date: 2023-02-22 17:06:51.584695

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f1db4f15b5f8'
down_revision = 'd405c6cb616b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('raw_message', mysql.LONGTEXT(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'raw_message')
    # ### end Alembic commands ###
