"""changed synced column from boolean to smallint

Revision ID: 5fcb672f9112
Revises: f1db4f15b5f8
Create Date: 2023-08-10 09:06:02.159407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fcb672f9112'
down_revision = 'f1db4f15b5f8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
