"""init

Revision ID: fd8b14a71c62
Revises: 
Create Date: 2023-01-22 10:10:39.314950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fd8b14a71c62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_data',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('content', mysql.LONGTEXT(), nullable=False),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_raw_data_uid'), 'raw_data', ['uid'], unique=False)
    op.create_table('order',
    sa.Column('created_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('uid', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('test_id', sa.String(length=50), nullable=True),
    sa.Column('keywork', sa.String(length=50), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('result_date', sa.String(length=25), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('is_sync_allowed', sa.Boolean(), nullable=False),
    sa.Column('synced', sa.Boolean(), nullable=False),
    sa.Column('sync_comment', sa.String(length=255), nullable=True),
    sa.Column('raw_data_uid', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['raw_data_uid'], ['raw_data.uid'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_index(op.f('ix_order_uid'), 'order', ['uid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_uid'), table_name='order')
    op.drop_table('order')
    op.drop_index(op.f('ix_raw_data_uid'), table_name='raw_data')
    op.drop_table('raw_data')
    # ### end Alembic commands ###
